# Generated by Django 4.0 on 2022-04-25 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_label', models.CharField(max_length=200, verbose_name='label for url resource')),
                ('url', models.URLField()),
                ('notes', models.TextField(default='', verbose_name='notes for url resource content')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('public', models.BooleanField(default=False, verbose_name='specifies if Link is supposed to be displayed for anonymous users')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='accounts.customuser')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
